### ISSUE TITLE
Add support for Elixir 1.7

### ISSUE THREAD

**Issue by jpagex** [meadsteve/white-bread#104]
For example, we have this warning with Elixir 1.7:
`warning: not passing the :switches or :strict option to OptionParser is deprecated`

**Comment by meadsteve** [comment]
@jpagex I can't actually see this warning myself. Can you confirm if you're on version 4.3.0 of whitebread as this is when 1.7 support was added.

**Comment by meadsteve** [comment]
Closing this now but let's re-open or create specific bugs when they come up 👍

**Comment by jpagex** [comment]
Maybe I was not on the version 4.3.0. I'll let you know if I encounter other warnings.
