### ISSUE TITLE
How do I test that a process has received a message?

### ISSUE THREAD

**Issue by oldfartdeveloper** [meadsteve/white-bread#16]
The **[ExUnit.Case](http://elixir-lang.org/docs/v1.0/ex_unit/ExUnit.Case.html)** documentation shows how a `context` object can be set up and, in the example, be populated in the `setup` etc as shown here:

```elixir
defmodule KVTest do
  use ExUnit.Case

  setup do
    {:ok, pid} = KV.start_link
    {:ok, [pid: pid]}
  end

  test "stores key-values", context do
    assert KV.put(context[:pid], :hello, :world) == :ok
    assert KV.get(context[:pid], :hello) == :world
  end
end
```

Where do I do those setups in the `default_context.exs` file that I've copied from yours?  The relevant part of the code I'm trying to figure out how to implement this in is:

```elixir
defmodule PaypalIpnForwarder.SenderSimulatorContext do
  use WhiteBread.Context
  alias PaypalIpnForwarder.Manager
  alias PaypalIpnForwarder.SenderSimulator

  when_ ~r/^the sender simulator sends (?<notification>.+) to the server$/, fn state, %{notification: notification} ->
    manager = state |> Dict.get(:manager)
    sender_simulator = Manager.sender_server(manager)
    SenderSimulator.notify(sender_simulator, notification)
    {:ok, state}
  end

  then_ ~r/^the server sends an IPN acknowledgement to the sender simulator as an HTTP request$/, fn state ->
    manager = state |> Dict.get(:manager)
    sender_server = Manager.sender_server(manager)

    ################################################################
    ######## HERE!!! What am I missing or doing wrong here? ########
    ################################################################
    assert_receive({:acknowledge, "IPN Notification"}, 5_000, "Sender server didn't receive acknowledgement")

    {:ok, state}
  end
```

When I execute `mix white_bread.run`, I get this error:

---

  - Test IPN notification handshake between sendor simulator and the server --> the server sends an IPN acknowledgement to the sender simulator as an HTTP request: Sender server didn't receive acknowledgement. The process mailbox is empty.

---

The problem is that I don't know how to identify the process `pid` that I'm testing to receive the `:acknowledge` notification to **ExUnit**.  I'm guessing that the `WhiteBread.Context` needs to make available a `setup` callback so that I can set up the `ExUnit` test there.

I've really enjoyed using `white_bread`; for what I've been able to use it for thus far, it has been easy and transparent to use.  Thanks!

**Comment by meadsteve** [comment]
Hi @oldfartdeveloper (side note: I feel bad typing your name :smile: ) firstly I'm glad you've been enjoying using this tool.

I've not actually used white bread to assert any message sending myself yet. However regarding the setup callback I think this is mainly my fault on the documentation. There are already two possible points that could be used:

The first is executed when each feature starts an is defined as below. It takes no arguments and generates a new clean state.
```elixir 
feature_starting_state fn  ->
  %{feature_pid: self}
end
```

and the second is done at the start of of each scenario and receives the starting state from the previous:

```elixir 
scenario_starting_state fn feature_state ->
  feature_state |> Dict.put(:scenario_pid: self)
end
```

The pid in the current implementation would be the same. Are either of these callbacks suitable for the setup you need to do?

**Comment by oldfartdeveloper** [comment]
Hi Steve,

I like your answer. After some hard thinking about it, I realize that I missed how `ExUnit.Case` sets up the `context` object; I missed that it passes it in as an argument to the `test` statement.

So you are correct: I simply need to do something similar using one of your "starting states" and it should work fine.

I'll try it and let you know how it goes.  If it works, I'll submit a PR w/ documentation on how to do it.

Again, thanks for providing your answer; it helped me realize what was really going on.
