### ISSUE TITLE
Step function names

### ISSUE THREAD

**Issue by pfac** [meadsteve/white-bread#2]
Hey,

Was just checking this project and while it seems very interesting the decision to append an underscore to the names of the functions handling the steps strikes me as very odd.

Is there a particular reason why you had to do this (and I missed it) or is it just a design preference?

Cheers

**Comment by meadsteve** [comment]
@pfac I would actually prefer to not have the underscores too. However ```when``` is already taken by guard clauses. Any alternative suggestions are welcome.

**Comment by pfac** [comment]
@meadsteve never realized that you couldn't have a function named `when`. Makes perfect sense then.

As for suggestions, I apparently have a few (all ocurred while writing this reply :stuck_out_tongue_closed_eyes:).

### Generic step function

You could use a generic step handling function for when, like

    step "when", ...

and leaving `then` and `given` as alias functions. But I understand that you would be giving up consistency for aesthetics, so that's out of the equation.

### Synonyms

Alternatively you could use a synonym instead, such as `on` or `if` (works well semantically but may cause confusion). Still, any synonym would require you to explicitly state that caveat in the README to avoid confusions since gherkin uses "when".

### `__using__`

Apparently there is nothing against a module named `When`, and since the original Ruby implementation also uses the capitalized word, it would be a good fit. With the macro `__using__` the interface could be something like

    use When, ...

Not as good as a `when` method but I find it somewhat elegant.

Still, these are only suggestions. Your reasoning is perfectly valid given the constraints of the language. Feel free to close this issue as soon as you feel the discussion is not worth it anymore.

And thanks for the fast reply :+1:

**Comment by meadsteve** [comment]
Good suggestions. I think I'll keep this issue open (at least for now) as I think it'll be good to nail this down before I bump the version to ```1.0.0```. 

I quite like your step suggestion. So the definitions could look like:
```elixir
step "when", "I press the coffee button", fn state ->
    {:ok, state |> Dict.put(:coffees_served, 1)}
end
```
My only concern is that it adds more text/noise to the file.

**Comment by pfac** [comment]
Agree, it does add some noise. I was here trying to explore an approach with module attributes, or using a tuple list like in Ecto, but it seems you can't make a module attribute `@when`, and the tuple list even adds more noise.

There is also the alternative of imitating the language itself, and use macros `defstep`, `defwhen`, `defgiven`, ...

``` elixir
defwhen state, "I press the coffee button" do
  {:ok, state |> Dict.put(:coffees_served, 1)}
end
```

Since you are clearly more experienced than me with the language I'll rely on your judgement to tell me if this is even feasible.

**Comment by danmarcab** [comment]
Hi, 
Or maybe you could do the same as in the ruby gem turnip https://github.com/jnicklas/turnip.
Every `When`, `Given`, `And` ... is just implemented as a `step`. That way you can reuse the same step for different contexts.

**Comment by meadsteve** [comment]
@danmarcab I'm not sure I'm very keen on the turnip approach. Most other gherkin/cuke implementations separate out the given/when/then from the rest of the string to be matched. This approach makes sense to me as the first word in the step has a special meaning.

As an aside behind the scenes all the Given, Whens etc get treated the same anyway.

**Comment by danmarcab** [comment]
Fair enough @meadsteve, at the end it's a matter of flavour, I was just giving you another alternative :+1:

**Comment by meadsteve** [comment]
@danmarcab no worries.  Thank you for the suggestion/alternative.

**Comment by meadsteve** [comment]
I've been thinking about this and I think I'm going to leave them as they are for now.
