### ISSUE TITLE
Progress report behaviour is a bit weird

### ISSUE THREAD

**Issue by leiyangyou** [meadsteve/white-bread#26]
Hi @meadsteve 

I'm running a couple hound test with white-bread, 
it looks like progress reporting doesn't happen as each scenario is run but happens each feature is run

**Comment by meadsteve** [comment]
@leiyangyou thanks I'll take a look. I've not really given much attention to the progress reporting.

**Comment by meadsteve** [comment]
This is fixed by ace0feb0595196d8adcd2cccabe912b925954b8a
I'll be releasing this and #27 as a patch release in the next few days.
