### ISSUE TITLE
Failures appear in red

### ISSUE THREAD

**Issue by javflores** [meadsteve/white-bread#28]
I'm trying Whitebread to write my acceptance tests.
One of the things I noticed is that failures don't appear in red in the console.

Is it possible to set up colors for the output of tests?
If not I'm happy to submit a pull request to implement that.

**Comment by meadsteve** [comment]
@javflores to be honest I just never got around to adding colours to the console. Happy to receive a PR. A good starting point would be this module lib/white_bread/outputers/console.ex as it handles output to the console.

**Comment by meadsteve** [comment]
Fixed by #29 released in 2.2.0
