### ISSUE TITLE
Create config for mapping multiple contexts on to features [Suites]

### ISSUE THREAD

**Issue by meadsteve** [meadsteve/white-bread#31]
Inspired by the suites concept in behat: 
http://docs.behat.org/en/latest/guides/5.suites.html
There should be some core config file that looks like the following:
```elixir
defmodule WhiteBread.Example.Config do
  use WhiteBread.SuiteConfiguration

  suite name:          "Default",
        context:       WhiteBread.Example.DefaultContext,
        feature_paths: ["features/"]

  suite name:          "Alternate",
        context:       WhiteBread.Example.AlternateContext,
        feature_paths: ["features/"]

  suite name:          "Alternate - Songs",
        context:       WhiteBread.Example.AlternateContext,
        feature_paths: ["features/"],
        tags:          ["songs"]
end
```

**Comment by rkotze** [comment]
Just to clarify a few of things most with the pluralisation as its not so obvious in the documentation: Lets take for example `core_features`: 

- The `paths` property points to a directory containing `.feature` files - but can I list multiple paths? 
- Then `contexts` points one context file in that directory or can you list multiple context files there?
- Also would I be able to run all the tests at once? e.g. `mix whitebread.run --suites all`

**Comment by meadsteve** [comment]
@rkotze good clarifications. I've update the example in the description appropriately. 

I think Paths and Contexts should both allow multiple entries. It seems to me to give the most flexibility without losing any explicitness. 

Regarding running I imagined that that ```mix whitebread.run``` would by default run all suites and then ```mix whitebread.run --suite specific_suite``` would run only the specified one.

**Comment by meadsteve** [comment]
Though actually on reflection, as the contexts define the starting state I may force people to use a single context as an entry point. They could still be composed of multiple contexts using:
```elixir

defmodule UserWebContext do
  use WhiteBread.Context

  subcontext UserContext
  subcontext WebContext

  feature_starting_state fn  ->
    %{feature_state_loaded: :yes}
  end

  scenario_starting_state fn feature_state ->
    feature_state |> Dict.put(:starting_state_loaded, :yes)
  end

  scenario_finalize fn _state ->
    # Do some finalization actions
  end

end
```
