### ISSUE TITLE
Add setting for "one context per feature file"

### ISSUE THREAD

**Issue by meadsteve** [meadsteve/white-bread#33]
After discussions with @rkotze we've decided that some users have use case of one context per feature file. This can follow on from the work in #31 and could work by having the following as a config:
```elixir
defmodule WhiteBread.Example.Config do
  use WhiteBread.SuiteConfiguration

 load_one_context_per_feature namespace: WhiteBread.Example

end
```

This would then scan the features and map the paths such that ```feature/directory/my_thing.feature``` loads context ```WhiteBread.Example.Directory.MyThingContext```

**Comment by meadsteve** [comment]
I also don't see any reason why this can't be combined with extra suites:
```elixir
defmodule WhiteBread.Example.Config do
  use WhiteBread.SuiteConfiguration

 load_one_context_per_feature namespace: WhiteBread.Example.Standard

  suite name:          "Special",
        context:       WhiteBread.Example.SpecialApiContext,
        feature_paths: ["features/thing/"]


end
```

**Comment by rkotze** [comment]
@meadsteve This looks great :+1:

**Comment by meadsteve** [comment]
Thinking about this a bit more it might be useful to have an (optional?) path here:
```elixir
defmodule WhiteBread.Example.Config do
  use WhiteBread.SuiteConfiguration

 load_one_context_per_feature namespace: WhiteBread.Example,
                              path: "features/something"

end
```
If this is ommited then I think it would just load everything in features/

**Comment by rkotze** [comment]
Is the path in the example the place where to start looking for the features?
Maybe instead of the namespace we use the path as the point to start and anything that has a feature file gets loaded in with the matching context.exs file?

**Comment by meadsteve** [comment]
@rkotze maybe namespace isn't the right key. namespace_prefix maybe? in the example I gave it would .for a feature called ```features/something/thing.feature```, load ```WhiteBread.Example.Thing```.

Regarding context file loading: if the context files (as .ex) are in the lib/ they will get compiled by mix as normal. I've also added code so that any .exs files in ```features/contexts``` get loaded.

**Comment by javflores** [comment]
Hi @meadsteve, thanks for this great framework! I'm trying to use this new functionality.

This is my config.exs:
```
defmodule GameEngine.Features.Config do
	use WhiteBread.SuiteConfiguration

	suite name: "Computers play game",
        context: GameEngine.Features.ComputersPlayGameContext,
        feature_paths: ["features/context/"]

    suite name: "Human versus computer game",
        context: GameEngine.Features.HumanVersusComputerGameContext,
        feature_paths: ["features/context/"]
end
```

Then under features/context folder I have several files named: computers_play_game_context.exs and human_versus_computer_game_context.exs

My features live in the features folder: computers_play_game.feature and human_versus_computer_game.feature

In the mix file of my app I have the following to run all the features at once:
```
defp aliases do
    [acceptance: ["white_bread.run --context features/contexts/computers_play_game_context.exs", 
                  "white_bread.run --context features/contexts/human_versus_computer_game_context.exs"]]
  end
```

So what is happening is that whitebread runs randomly one feature or the other. And for the one that doesn't run I get the error:
```
Human moves ---> failed                                                                       
1 scenario failed for Human versus computer game                                              
  - Human moves --> undefined step: I have started a human versus computer game implement with
                                                                                              
given_ ~r/^I have started a human versus computer game$/, fn state ->                         
  {:ok, state}                                                                                
end
```
It is like it isn't able to load the second context file.
Any tip or clue? It is likely that I am doing something wrong in the set up.
Cheers

**Comment by meadsteve** [comment]
@javflores two things.
* (Documentation issue.) With the suite config you don't need to specific the contexts at all as flags. It should automatically load each context from the suite config. So :
```elixir
defp aliases do
    [acceptance: ["white_bread.run"]]
end
```

* Automatic one context per feature file hasn't actually been implemented yet. So the suite config you have will run all all features against the supplied context so maybe instead you want to move the features in to sub directories so:
```elixir
defmodule GameEngine.Features.Config do
    use WhiteBread.SuiteConfiguration

    suite name: "Computers play game",
        context: GameEngine.Features.ComputersPlayGameContext,
        feature_paths: ["features/computers_playing/"]

    suite name: "Human versus computer game",
        context: GameEngine.Features.HumanVersusComputerGameContext,
        feature_paths: ["features/humans_playing/"]
end
```

**Comment by javflores** [comment]
Thanks for the answer @meadsteve. Great to have this framework to write acceptance tests in Elixir apps.

**Comment by meadsteve** [comment]
@javflores no problem! When I get some time I'd love to improve(/actually add some) the documentation. It's really useful to know what problems people have run in to as this is something that could be addressed with a better "getting started guide".
