### ISSUE TITLE
scenario_starting_state too late

### ISSUE THREAD

**Issue by revati** [meadsteve/white-bread#44]
Hello, i have problem when running tests.

I start my database in memory before each scenario. When scenario finishes i kill that task.
```elixir
  scenario_starting_state fn state ->
    task = Task.async fn ->
      Mix.Shell.cmd("cd event_store && ./run-node.sh --mem-db", fn _ -> nil end)
    end

    state |> Dict.put(:event_store, task)
  end
```

I also have supervised database GenServer which, as i understand, because of beeing supervised, is started immediately after application is started. But it can't connect to db port, because db isn't started yet.

So how could i make sure that db is started for tests before supervisors spawn workers? Or are there any other ways?

P.S. I am new to elixir and otp.

**Comment by burmajam** [comment]
I think you should start event_store in test/test_helper.ex file before ExUnit.start call

**Comment by revati** [comment]
It doesn't seem to work. When i run `mix white_bread.run` it ignores `test/test_helper.exs` file. I tried to put there `IO.inspect` and even break syntax.

Nothing changed.

**Comment by burmajam** [comment]
How about creating your own mix task then which would start event_store and then run mix test task? I'm just thinking loud. Take a look @ http://elixir-lang.org/docs/stable/mix/Mix.Task.html for more info how to create your own mix task.

**Comment by meadsteve** [comment]
@revati you could run white_bread with the ```--no-start``` (https://github.com/meadsteve/white-bread/blob/master/lib/mix/tasks/white_bread.run.ex#L64) option. 
Then in feature or scenario starting function you could start the db then start your app manually after waiting for the db to come up.

Does that help? Or have I misunderstood the issue?

**Comment by meadsteve** [comment]
@revati Are you still having this problem?

**Comment by revati** [comment]
It is ok now :)
