### ISSUE TITLE
power_assert support

### ISSUE THREAD

**Issue by Angry-Potato** [meadsteve/white-bread#46]
I am currently using white_bread in conjunction with power_assert and notice the formatting for assertion failures isn't lined up correctly, I had a bash at fixing it locally and putting a newline in the WhiteBread.Formatter.FailedStep AssertionError test function like so:

  def text(_, step, assertion_failure) do
    %{text: step_text} = step
    %{message: assestion_message} = assertion_failure
    "#{step_text}: \n#{assestion_message}" # <----- in there
  end

lined it up nicely, is this something you'd be willing to change?

**Comment by meadsteve** [comment]
@Angry-Potato the general output formatting is something that needs a lot of love. So I'd be more than happy to accept a PR with your suggestion :+1:
