### ISSUE TITLE
Support for async tests

### ISSUE THREAD

**Issue by campezzi** [meadsteve/white-bread#49]
Is it possible to run features/scenarios concurrently in white-bread? If not, do you think it would be possible and/or simple to add that functionality into the library?

Thanks!

**Comment by meadsteve** [comment]
@campezzi good idea! I've started implementing it here #50 . But I want to disable it by default and put it behind a config of some kind before I merge it in.

**Comment by campezzi** [comment]
Yes, making everything async by default would probably have backward-compatibility issues (old features breaking due to changes to global state etc). I haven't looked into the source yet, but looking forward to help any way I can :)

**Comment by meadsteve** [comment]
@campezzi @pragmaticivan I've released a basic version of this as 2.7.0.
By default everything will run as it was before. However any suite setup with the following config will have all features and scenarios run in their own processes:

```elixir
  suite name:          "Default context",
        context:       WhiteBread.Example.DefaultContext,
        feature_paths: ["features/"],
        run_async:     true
```
https://github.com/meadsteve/white-bread/blob/master/features/config.exs#L13

```elixir
  context_per_feature namespace_prefix: WhiteBread.TestContextPerFeature,
                      entry_path: "features/test_context_per_feature/",
                      extra: [
                        run_async: true
                      ]
```
https://github.com/meadsteve/white-bread/blob/master/features/config.exs#L7

**Comment by campezzi** [comment]
Thank you for that - I'll give it a go!

**Comment by meadsteve** [comment]
@campezzi any feedback let me know. I haven't used it myself very much.

**Comment by follmann** [comment]
Hey Steve, I just begun using the async feature with Ecto 2.0 RC and Wallaby. It works, but in my setup errors get swallowed since the default timeout of 5000 ms of `Task.await` kicks in before. It would be good to be able to configure that timeout. Thanks!
