### ISSUE TITLE
Database left dirty after every feature run

### ISSUE THREAD

**Issue by ngw** [meadsteve/white-bread#62]
Hello, I'm using white-bread to run features in my Phoenix project.
One of the features adds data to the DB using a simple form and Hound. 
I would like the feature to run inside some kind of "transaction" and delete all data every after every run, is it possible?

My configuration is nothing fancy:
white-bread config.exs - https://gist.github.com/ngw/493d0fbe743fba3fa6766cbe29ecd38c
conn_case - https://gist.github.com/ngw/65cc480c2e48f31ee465975d5ee32b34

I run white-bread with: MIX_ENV=test mix white_bread.run

Am I doing something wrong?

**Comment by ngw** [comment]
Still, it's a little bit confusing on how to understand what to use and how.
This is what I got right now:

    scenario_starting_state fn state ->
      Hound.start_session
      state
    end

    scenario_finalize fn state ->
      Hound.end_session
      state
    end

    feature_starting_state fn ->
      Ecto.Adapters.SQL.Sandbox.checkout(Owl.Repo)
      Ecto.Adapters.SQL.Sandbox.mode(Owl.Repo, {:shared, self()})
    end

But still, the database is left "dirty" after each feature run. What am I doing wrong?

**Comment by meadsteve** [comment]
@ngw how did you get on with this? Did you find a way to tidy the DB up after each run? It might be a useful thing for me to document as part of an integration guide.

**Comment by raycheung** [comment]
@ngw I suspect your DB was still dirty because the sandbox connection didn't checked in back into the pool, which basically rollback the transaction.

I resolved similar issue with:
```elixir
  scenario_starting_state fn state ->
    Ecto.Adapters.SQL.Sandbox.checkout(Imagine.Repo)
    Ecto.Adapters.SQL.Sandbox.mode(Imagine.Repo, {:shared, self()})
    state
  end
```

then:
```elixir
  scenario_finalize fn state ->
    Ecto.Adapters.SQL.Sandbox.checkin(Imagine.Repo)
  end
```

**Comment by meadsteve** [comment]
I'm closing this issue for now as it's not directly an issue as it's how the software is intended to run but there's possible a future enhancement here. Maybe a package to provide a white-bread <> ecto integration.
