### ISSUE TITLE
Always green when outline

### ISSUE THREAD

**Issue by ngw** [meadsteve/white-bread#64]
Hi, I've marked a scenario as a Scenario Outline, and even if I didn't even implement the steps when I ran it it was always green.
Is this wanted or a bug?

**Comment by meadsteve** [comment]
Sounds like a bug to me. @ngw could you put a simple example here?

**Comment by ngw** [comment]
https://gist.github.com/ngw/0aaf615496fa6a5c041665febee09e02

**Comment by meadsteve** [comment]
This is fixed in master but I'll cherry pick the changes back and do a release on 2.x

**Comment by meadsteve** [comment]
Released as 2.8.1
