### ISSUE TITLE
Scenario outlines don't set state properly

### ISSUE THREAD

**Issue by marnen** [meadsteve/white-bread#73]
I'm using scenario outlines in White-Bread 2.8.1, and it appears that unlike straight scenarios, the `scenario_starting_state` hook never sets the scenario starting state for outlines. Is there another hook I should be using for this purpose, or is this a bug?

**Comment by meadsteve** [comment]
@marnen this sounds like a bug. My intention was that scenario_starting_state would be called for each scenario as part of the outline.

**Comment by marnen** [comment]
Good to know. I'll try to fix it (although I'm a total beginner in Elixir...).

**Comment by marnen** [comment]
I think #76 will do the trick.

**Comment by meadsteve** [comment]
This will be fixed thanks to #76. It will be released in the pending 3.x release. 
I hope to have this release out for the end of the year (family life dependant).
